# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         o2sms
version:      3.01
version_from: bin/o2sms
installdirs:  site
requires:
    Crypt::SSLeay:                 0
    Getopt::Long:                  0
    IO::Socket::SSL:               0
    Net::SSLeay:                   0
    Storable:                      0
    Term::ReadLine:                0
    TestGen4Web::Runner:           0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
